# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MASSPlugin
                                 A QGIS plugin
 Algorithm for fast product kernel density estimation and spatial analysis of large geospatial datasets

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-18
        copyright            : (C) 2026 by MASS-group
        email                : yovela12138@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MASSPlugin class from file MASSPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mass_fast_product_kernel_density_analysis import MASSPlugin
    return MASSPlugin(iface)
